### ISSUE TITLE
Implement refresh JWT token handling in frontend

### ISSUE THREAD

**Issue by kristoferlund** [givepraise/praise#1007]
Currently we redirect the user to a generic error handling page for most unexpected errors. The expiry of JWT tokens is an expected error and needs custom handling. 

When we get such an error we should delete the current token and redirect user to login page. 

ps. Later we will implement refreshToken handling to avoid this alltogether.

**Comment by kristoferlund** [comment]
This is what you currently get. No good. :)

![Image](https://github.com/givepraise/praise/assets/9698363/179085ef-e347-4434-a8b2-e1a98f23ebe7)

**Comment by kristoferlund** [comment]
Yes, all errors have unique codes. Should be ok to add that condition.

<img width="538" alt="image" src="https://github.com/givepraise/praise/assets/9698363/6ccf5d42-0ed2-49b4-824a-9b4e0be07de6">

**Comment by kkatusic** [comment]
@kristoferlund I can reproduce error, but there isn't redirection to error page, 404, anymore.
Should we close this?

**Comment by kristoferlund** [comment]
@kkatusic renamed this issue
