### ISSUE TITLE
Use db template when creating new community

### ISSUE THREAD

**Issue by kristoferlund** [givepraise/praise#1042]
Currently when we create a new community, we create a clean db and run all migrations on that db, ca 1 minute That process i a bit too slow, we don't want the user to have to wait that long when creating.

Can we instead have an always up to date db template that we use and just copy it for new communities?

**Comment by kristoferlund** [comment]
@mohammadranjbarz this might be an issue for you as well?

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz this might be an issue for you as well?

Cool, such a nice idea!!

**Comment by mohammadranjbarz** [comment]
@kristoferlund  I put log before and after running migrations when creating new communities and ran tests

```
  async create(communityDto: CreateCommunityInputDto): Promise<Community> {
    assertOwnersIncludeCreator(communityDto.owners, communityDto.creator);
    await this.assertCommunityNameAvailable(communityDto.name);
    const community = new this.communityModel({
      ...communityDto,
      isPublic: true,
      // it produces a random string of 5 characters
      discordLinkNonce: randomBytes(5).toString('hex'),
      database: communityDto.hostname.replace(/\./g, '-'),
    });
    await community.save();
    console.time("Create new Db for community");
    // Create and setup community database
    const migrationsManager = new MigrationsManager();
    await migrationsManager.migrate(community);
    console.timeEnd("Create new Db for community");

    return community;
  }
```
but I sat it just takes less than a second to run migrations, are you sure it's the reason of taking too much time on setup web?
I couldn't run setupWeb on my machine ( I couldn't find the repository either) to test it in that way, but it seems we don't need to optimize it
<img width="991" alt="Screen Shot 1402-03-03 at 12 01 57" src="https://github.com/givepraise/praise/assets/9850545/8cc4b88f-b860-4a3e-af08-95fb1629c5d1">

**Comment by mohammadranjbarz** [comment]
@kristoferlund  I did lots of testing, on my machine , on staging, and I can aasure you creating community doesn't take too much time and it does it less than 1-2 seconds, as I couldn't generate the problem you reported I think we can leave it to be like that, because it's good now, maybe the thing that you save has had another reason that it doesn't exist now


In below screen shot you can that it took just **1.15s**
https://dev.givepraise.xyz/setup
<img width="1440" alt="Screen Shot 1402-03-04 at 15 50 28" src="https://github.com/givepraise/praise/assets/9850545/b5882d6d-0bb4-426d-92c3-9b52c0582a8f">

**Comment by kristoferlund** [comment]
Ok great, thanks for investigating! 

I believe issue is with setup we. Perhaps it has something to do with cold starts. I have asked @marthendalnunes:

> When creating a new community using the form on the website after a longer period of inactivity, the form often times out. I thought it was something with our database migrations but.. creating a new community db takes less than a second. And when trying a second time all works well, creation is fast. Could there be an issue with slow Next.js api cold starts? The first time the serverless function runs (after a period of being idle) it takes some time to start up?

**Comment by marthendalnunes** [comment]
@kristoferlund cold starts, I can check the code today, moving it to the edge will fix it (if what you're using on the api endpoints is supported by the runtime ofc)

**Comment by kristoferlund** [comment]
> @kristoferlund cold starts, I can check the code today, moving it to the edge will fix it (if what you're using on the api endpoints is supported by the runtime ofc)

The api endpoint is mostly a http "forward" request using fetch so it should be good.

**Comment by marthendalnunes** [comment]
ok, checking this afternoon and opening the PR today

**Comment by kristoferlund** [comment]
Issue solved, see https://github.com/givepraise/web/pull/61.
Closing.
