### ISSUE TITLE
REVERT -> Show link message when trying to interact with bot that has not yet been linked with community

### ISSUE THREAD

**Issue by kristoferlund** [givepraise/praise#1046]
There are two possible scenarios:

1. You have created a Praise Community but did not complete the bot linking process
2. You have not created a Praise Community yet but invited the bot anyway

Bot scenarios need to be handled.

## Linking not completed

![Image](https://user-images.githubusercontent.com/9698363/241888495-735420fd-1326-4d0f-8714-386af11600e5.png)

## No community created

- Link to https://givepraise.xyz/setup

![Image](https://user-images.githubusercontent.com/9698363/241889947-2ac7b9c7-b834-450b-8d95-c8cc7df22854.png)

**Comment by kristoferlund** [comment]
@Vyvy-vi could you take this?

**Comment by Vyvy-vi** [comment]
sure
