### ISSUE TITLE
Activate account when praising the first time

### ISSUE THREAD

**Issue by kristoferlund** [givepraise/praise#1048]
We want to make it easier for users to activate. Instead of requiring a separate activation step, allow for activating the first time you praise as well.

1. User tries to praise
2. API: User has not activated their account
3. Notify user with activation message: 
  - not yet activated
  - click here to activate
  - retry button
  - When done activating click retry button
4. User clicks retry after activating
5. Praise sent

**Comment by Vyvy-vi** [comment]
I'd like to work on this
