### ISSUE TITLE
Track metrics

### ISSUE THREAD

**Issue by kristoferlund** [givepraise/praise#1049]
Examples:

# API

## Users

User activated

## Praise

Praise given

# Dashboard

- Page loads
- Track how many use the dashboard
- Etc

**Comment by kristoferlund** [comment]
Integrate with Plausible, https://plausible.io/

**Comment by kkatusic** [comment]
Why?

**Comment by kristoferlund** [comment]
Tell me more

**Comment by kkatusic** [comment]
GA is the best, top one, but if we don't need all feature that GA provide and you know that Plausible already is using on some other GM project I'm ok with that :)

**Comment by kristoferlund** [comment]
Ah, that is what you meant. We can't give Google our usage data out of principle :)

**Comment by kkatusic** [comment]
You got my vote 👍

**Comment by mohammadranjbarz** [comment]
@kristoferlund 

Plausible Analytics doesnt provide much APIs, so we can't use it in our API projects, if you see their docs, they just have some GET requests for getting some analytics not for adding new record for events, it seems too minimal, are you sure we can do all we want with their SDK ?

**Comment by kristoferlund** [comment]
@mohammadranjbarz did you see this page? POST requests are available.

https://plausible.io/docs/events-api

My thought was, if we can track regular page views etc - the regular stuff on the frontend, and we can track custom events in the API and discord-bot we should be good.

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz did you see this page? POST requests are available.
> 
> https://plausible.io/docs/events-api
> 
> My thought was, if we can track regular page views etc - the regular stuff on the frontend, and we can track custom events in the API and discord-bot we should be good.

Oh you are right, thanks

**Comment by kristoferlund** [comment]
@mohammadranjbarz, for the API, to begin with we want to track events for all POST/PATCH/DELETE endpoints right. Or GET endpoints as well, what do you say?

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz, for the API, to begin with we want to track events for all POST/PATCH/DELETE endpoints right. Or GET endpoints as well, what do you say?

We can give it a shot, so do you mean it is better to define some middleware to call after those endpoints?

**Comment by kristoferlund** [comment]
@mohammadranjbarz Yes, perhaps a middleware is a good solution, what do you think?
