### ISSUE TITLE
Bring back the quantification call out box

### ISSUE THREAD

**Issue by kristoferlund** [givepraise/praise#1061]
This box at the first page has gone missing. Bring it back

![Image](https://user-images.githubusercontent.com/9698363/243591535-a9cd0ea5-5b17-44b2-b109-a36d502ce666.png)

**Comment by kristoferlund** [comment]
- fetch period list does not reveal quantifiers
- fetch period details to get quantifiers
- Look through list of periods
- If status is quantify, fetch details
- Check if user is in quantifier list 
- Show box if that is the case

**Comment by kkatusic** [comment]
@kristoferlund you finished this?

**Comment by kkatusic** [comment]
Sorry, it stays in dashboard for some reason
