### ISSUE TITLE
`/admin announce` don't work

### ISSUE THREAD

**Issue by kristoferlund** [givepraise/praise#1063]
Tested in the giveth discord, bot gets stuck in "Thinking…" when trying to send announce to period quantifiers.

**Comment by kristoferlund** [comment]
@Vyvy-vi  Command is still having issues. This is reported from Mitch:


![Image](https://github.com/givepraise/praise/assets/9698363/a06ac37e-33e4-4ce1-8336-0eae091996dc)

**Comment by Vyvy-vi** [comment]
Is this with the receivers option or with the assigned quantifiers option?

**Comment by kristoferlund** [comment]
@Vyvy-vi  
> Is this with the receivers option or with the assigned quantifiers option?

Franco / Giveth would know more. Also Mitch ran into this issue.
