### ISSUE TITLE
Redirect URLs for communities with custom domains

### ISSUE THREAD

**Issue by kristoferlund** [givepraise/praise#1072]
```
tec.givepraise.xyz -> praise.tecommons.org
giveth.givepraise.xyz -> praise.giveth.io
commonsstack.givepraise.xyz -> praise.commonsstack.org
```

Can we do the redirect at the cloudflare level?

https://developers.cloudflare.com/fundamentals/get-started/basic-tasks/manage-domains/redirect-domain/

**Comment by kristoferlund** [comment]
@mhmdksh can you have a look at this one?

**Comment by mhmdksh** [comment]
@kristoferlund 

What is the main reason we want to achieve that?

Our saas api backend can perfectly handle Custom Domains if:
1- A CNAME Record is added
2- The Domain is found in our DB

Please check this section of the Documentation.

<img width="960" alt="image" src="https://github.com/givepraise/praise/assets/52987806/36669cf1-8514-4255-85b2-911b576c6778">

**Comment by mhmdksh** [comment]
Also this solution requires us to manage our communities whole DNS. Which is mentioned in the first step of the tutorial in the link

<img width="558" alt="image" src="https://github.com/givepraise/praise/assets/52987806/d2f73867-05de-4ccb-80da-dd44fe988b86">

<img width="1045" alt="image" src="https://github.com/givepraise/praise/assets/52987806/da3210fe-c0c6-4b1a-9b41-832d63db71f8">

Do we really need that?

**Comment by kristoferlund** [comment]
@mhmdksh Yes, to domain setup with CNAME works great. The redirect is for all the people having the old link if a community changes the domain. 

<img width="515" alt="image" src="https://github.com/givepraise/praise/assets/9698363/518372e5-8b1d-4333-b5c7-11fadcb94392">

Also, in messages like these that have been sent on Discord the link doesn't work after domain change. 

Sorry if being overexplicit:
1. Community starts at `somecommunity.givepraise.xyz`
2. Some time pass, they use Praise
3. Community change domain to `praise.somecommunity.io`
4. Old links don't work

**Comment by mhmdksh** [comment]
@kristoferlund Ok it's done. But, please note the below:

This has been configured through creating forwarding rules: https://developers.cloudflare.com/support/page-rules/configuring-url-forwarding-or-redirects-with-page-rules/

But note in our account we can get a maximum of 3 forwardings, so it has a limit. Check the below Screenshot:

<img width="1049" alt="image" src="https://github.com/givepraise/praise/assets/52987806/7c015e24-f619-4b6b-82f5-b15995de865b">

Please keep that in mind at the moment, as this is a temporary workaround/solution.

**Comment by kristoferlund** [comment]
Don't close, move to review first. :)

We need to handle the rest of the url as well.

`https://giveth.givepraise.xyz/praise/6489877512015dae7ed40df3``

Should redirect to:

`https://praise.giveth.io/praise/6489877512015dae7ed40df3`

And so on.

**Comment by mhmdksh** [comment]
@kristoferlund The full URI is handled now. Through these settings.

<img width="1423" alt="image" src="https://github.com/givepraise/praise/assets/52987806/671f4da6-7777-4116-b733-429d384e3b76">

Note, again that we can't add additional Custom Domain Redirects from Cloudflare. We reached our maximum quota, unless we buy more forwarding rules.

**Comment by kristoferlund** [comment]
Closing this now as done!
