### ISSUE TITLE
Praise Legacy CSV columns names problem

### ISSUE THREAD

**Issue by kristoferlund** [givepraise/praise#1082]
User reported problem after downloading Praise Legacy CSV file. He tried to run some script on that file, but few columns has name with underscore, before it was with the empty space.

**Comment by kkatusic** [comment]
@kristoferlund , sorry here it is:

- one of the first columns have underscore in its names:

![underscore](https://github.com/givepraise/praise/assets/1242145/c048eb07-e9fa-4360-b1e6-0328389cb3cc)

- old CSV format hasn't underscore in column names:

![no-underscore](https://github.com/givepraise/praise/assets/1242145/e25d771a-8dee-435f-92b2-7a284a89c956)

**Comment by kristoferlund** [comment]
@kkatusic, great! Then it can be easily fixed here: https://github.com/givepraise/reports/blob/main/reports/praise-legacy-full-export/report.js
