### ISSUE TITLE
Remove latest activity on /whois bot command

### ISSUE THREAD

**Issue by kkatusic** [givepraise/praise#1085]

**Comment by kkatusic** [comment]
When I use command `/whois` it is showing latest activity on February but that isn't true



![Image](https://github.com/givepraise/praise/assets/1242145/553fccfd-e137-4f76-b913-e42cce1cd75b)

**Comment by Vyvy-vi** [comment]
This field is using the last updated timestamp from mongoose

**Comment by kkatusic** [comment]
@Vyvy-vi can you be more specific, what database table? thx

**Comment by Vyvy-vi** [comment]
useraccounts

**Comment by kristoferlund** [comment]
One question here is what means "latest activity". Giving a praise, of course. Logging in to the dashboard? I guess any authenticated API interaction should count as "activity" and update this field. 

To me it sounds like we should create an API middleware to update activity on each authenticated interaction.  

@mohammadranjbarz perhaps have some input after fiddling recently with middlewares and interceptors.

**Comment by Vyvy-vi** [comment]
Q) Does that metric add much value? Perhaps it can be replaced by something more meaningful, like "lastActivePeriod", "total duties as quantifier", "total praises received / given"?

**Comment by kkatusic** [comment]
> This uses the `updatedAt` property returned by the API when fetching useraccounts https://github.com/givepraise/praise/blob/main/packages/api/src/useraccounts/schemas/useraccounts.schema.ts

thx, sorry for seeing this too late, Kristofer decided to remove that value ;)
