### ISSUE TITLE
Discuss: Can (and should) we separate dupe identification from quantification?

### ISSUE THREAD

**Issue by kristoferlund** [givepraise/praise#125]

**Comment by mattyg** [comment]
just a note that this would allow scrambling of all the praise within a period, making it difficult for quantifiers to identify the receiver of each praise item -- If that is important.

**Comment by kristoferlund** [comment]
It is and definitely isn't depending on who you ask (me for instance). Some argue that seeing the praise receivers names is an important signal that educates the quantifier about who does what in the community. And that the benefit of that greatly outweighs the risk of any skewed "buddy quantifications".
