### ISSUE TITLE
Sync user roles from api database to discord 

### ISSUE THREAD

**Issue by mattyg** [givepraise/praise#255]
**Roles to sync**
- QUANTIFIER -> quantifier (discord)
- USER -> praise giver (discord)

**Architecture**
- On recurring script --> sync all roles from praise api to discord
- On discord "set role" event -> call praise api to update user role

**Questions**
- Consider adding a new api user role 'GIVER' to sync to the 'praise giver' role on discord, instead of just than the 'USER' role. This will allow admins to *remove* praise powers from users without loosing their user data or access to historical data.

**Comment by kristoferlund** [comment]
Two layered approach
- Set Discord role when role is set in Praise admin
- Daily cleanup script, syncing Discord with api

**Comment by Vyvy-vi** [comment]
I could work on layer 1
