### ISSUE TITLE
Consolidate api type definitions

### ISSUE THREAD

**Issue by mattyg** [givepraise/praise#323]
Currently we have many different type definitions for a single kind of data model. This adds a lot of unnecessary complexity in the backend that make it cumbersome to introduce minor changes.

For example -- on the praise model we have:
- Praise
- PraiseDocument
- PraiseDto
- PraiseDtoExtended
- PraiseDetailsDto

We should seek to consolidate these type definitions and their usage to reduce complexity and development overhead -- even if it means we're fetching slightly more data than needed on the frontend.

**Comment by kristoferlund** [comment]
- If I remember correctly, `PraiseDtoExtended` is used only locally in one of the endpoints. 
- `PraiseDetailsDto` most likely can be merged with `PraiseDto`. 
- `Praise` I guess could be merged with `PraiseDocument`. But wouldn't it lead to conflicts in places where we don't expect to see all the mongoose stuff?
- `PraiseDto` I do think is wise to maintain as a separate interface so that we have explicit control over what gets sent to the client.

**Comment by mattyg** [comment]
> * If I remember correctly, `PraiseDtoExtended` is used only locally in one of the endpoints.
> * `PraiseDetailsDto` most likely can be merged with `PraiseDto`.
> * `Praise` I guess could be merged with `PraiseDocument`. But wouldn't it lead to conflicts in places where we don't expect to see all the mongoose stuff?
> * `PraiseDto` I do think is wise to maintain as a separate interface so that we have explicit control over what gets sent to the client.

PraiseDetailsDto, PraiseDto, and PraiseDtoExtended can be consolidated. I don't think it's worth the complexity and mental overhead unless it significantly reduces performance.

We should always be using the mongoose document type throughout the application. If we're using the Praise type it indicates an underlying problem with the implementation that may introduce bugs. The Praise type should only be used to define the mongoose schema.

**Comment by kristoferlund** [comment]
> We should always be using the mongoose document type throughout the api + discord-bot. The Praise type should only be used to define the mongoose schema. We should be able to rely on the constraints that mongoose puts on our data models throughout the application. If we're using the Praise type it indicates an potential problem that may introduce bugs.

Agreed 👍

> PraiseDetailsDto, PraiseDto, and PraiseDtoExtended can be consolidated.

Consolidated as in.. brought together into one, right? So, in the end there would be:

- Praise (Not to be used like you said, other than for defining PraiseDocument)
- PraiseDocument
- PraiseDto

In that case yes, sounds like a plan.

I imagine there will be situations where one Collection can be represented by more than one Dto though. A Dto can be defined to suite the special needs for an endpoint - representing a subset of the collection definition, adding some calculated value etc.

**Comment by mattyg** [comment]
Yes -- and the same for all other data models.

> I imagine there will be situations where one Collection can be represented by more than one Dto though. A Dto can be defined to suite the special needs for an endpoint - representing a subset of the collection definition, adding some calculated value etc.

Yes - if there is a significant performance cost to including the unneeded data (i.e. enough that it affects the user experience) then we should add another Dto, controller, transformer for the new data type.

Currently there is a lot of logic in the recoil store. We need to be able to make assumptions that the data in the recoil store reflects the expected data format. Introducing multiple formats for the same data model in the recoil store will add a lot of unnecessary complexity and boilerplate that makes it harder to reason about the application. It would mean redundant atom's to store another format of the same data, plus any selectors, callbacks, etc.

Or we can stop keeping all data in the recoil store, and instead store data within components for these cases where the data will not be used in any other context -- to avoid the extra complexity and overhead of managing data in recoil.

**Comment by mattyg** [comment]
> > We should always be using the mongoose document type throughout the api + discord-bot. The Praise type should only be used to define the mongoose schema. We should be able to rely on the constraints that mongoose puts on our data models throughout the application. If we're using the Praise type it indicates an potential problem that may introduce bugs.
> 
> Agreed +1

Unfortunately I think this is not going to be possible because we're using aggregate queries. The mongoose 'aggregate' function is just a proxy directly to mongodb -- none of the mongoose constraints are applied and it won't return a mongoose document.

We will need to migrate away from mongodb+mongoose entirely to get any kind of data constraints enforced throughout the entire application. :face_exhaling:
