### ISSUE TITLE
Make sure the bot signals if database is offline or other error

### ISSUE THREAD

**Issue by kristoferlund** [givepraise/praise#350]
The error message to the user don't need to be super detailed. Instead, use the events system to log a detailed error.

**Comment by kristoferlund** [comment]
`/praise xxx`

Bot replies:
`❌ Could not .. database error`

**Comment by Vyvy-vi** [comment]
Since the bot doesn't communicate with the database directly anymore, we could close this issue, and work on better error logging in #970 and #972
