### ISSUE TITLE
Multiple ethereum addresses per User

### ISSUE THREAD

**Issue by mattyg** [givepraise/praise#392]
Requires #391 

Allow a User to associate multiple other ethereum addresses with their account. Allow login by signing a message from any of those addresses.

Hopefully this will help prevent users from being locked out of their account due to a lost private key. Plus provide a clear way for users to recover their own accounts in the event of a lost private key.

**Comment by kristoferlund** [comment]
Yeah, we need to decide how to proceed here. Our ambition begins to sound very similar to what Ceramic is doing with [Self.ID](https://developers.ceramic.network/reference/self-id/). (Without the ambition to be a platform/framework of course)

Your Decentralised Identifier (DID) represents you - your identity. To the DID we attach a bunch of profile info. Plus verifiable proofs that tie your DID to various social media platform. Plus .. verified blockchain accounts - any number on any (at least many) different chains.

The future of identity management in the rewards space will (should) not be every rewards system building their own advanced id management system. It will be.. projects agreeing to use common identity solutions.

Is now the right time to hop on to Ceramic? I don't know. :)
