### ISSUE TITLE
API allows for duplicate Discord `User accounts` to be connected to one `User`

### ISSUE THREAD

**Issue by kristoferlund** [givepraise/praise#398]
<img width="693" alt="image" src="https://user-images.githubusercontent.com/9698363/168573299-ed1f3092-4bb0-4514-8cbb-10794786160f.png">

This happens when you start with a fresh db with dummy data and then activate your account using the bot. Two Discord user accounts.

**Comment by kristoferlund** [comment]
> I think it's correct behavior that multiple user accounts on the same platform can be linked to the same user. Why disallow it?

Perhaps (most likely) you are right. Me and Rudolf discussing this at length but I cannot remember what would be the reason to disallow it.

Closing this issue.

**Comment by mattyg** [comment]
> I'm opening this issue again. The real world usecase for this is an edge case. I have never heard about a situation where one individual is involved in one community under more than one discord user. Unless one user is some sort of test account or similar.
> 
> Even though it is not technically complex to allow multiple user accounts for one platform it creates complexity elsewhere.

Yeah good point. Makes sense to me!
