### ISSUE TITLE
The `/group-praise` command

### ISSUE THREAD

**Issue by Vyvy-vi** [givepraise/praise#472]
One of the warnings(`PRAISE_TO_ROLE_WARNING`), mentions the `/group-praise` command.
It would be great if we could talk about implementing that, or leaving it out and updating the setting's default value.

Q) Can this add any value?
This can add value to communities that contain many working groups with a small number of people.
It's easier for the praiseGiver to praise the whole group for tasks they can't find the contributors to.

Q) Is this needed?
Currently, it doesn't seem like anyone esp. requested this, but this idea was floating some time ago in the TEC Rewards group.

![Screenshot 2022-06-16 at 1 39 25 AM](https://user-images.githubusercontent.com/62864373/173918423-0d915e25-d003-4c98-b6a8-b98d68acb222.png)

**Comment by kristoferlund** [comment]
My personal opinion is that group Praise would do more harm than good. That does not mean we should not implement it. We have an issue defined already: #274 

But let's not implement it until someone requests it.
