### ISSUE TITLE
Sort praise receiver list on period quantification list based on no. of praise items

### ISSUE THREAD

**Issue by Vyvy-vi** [givepraise/praise#501]
![Screenshot 2022-06-26 at 7 34 39 PM](https://user-images.githubusercontent.com/62864373/175818159-e6848cd2-5e2d-457c-bc2f-11ffa1b5cab2.png)

It would be neat if we can have this sorted by no. of praise items (descending order?).
This isn't necessarily needed, but it's one of the things that would be nice to have, and could make the application look a bit more neater.

**Comment by kristoferlund** [comment]
What would be the reason to sort the list this way? Wouldn't alphabetical sort be more helpful? That would make it easier for someone wanting to find some specific receiver.

**Comment by kkatusic** [comment]
Is there option to add sort on the all columns?

**Comment by kristoferlund** [comment]
Certainly we could do that. But I would place that feature quit far down the list of what to implement next.

**Comment by Vyvy-vi** [comment]
I think it mght help quantifiers done with the bulk of their praise items faster.

**Comment by Vyvy-vi** [comment]
I think it might help quantifiers done with the bulk of their praise items faster.
