### ISSUE TITLE
Package Praise into one Docker container

### ISSUE THREAD

**Issue by kristoferlund** [givepraise/praise#543]
Is it possible?

https://docs.digitalocean.com/products/app-platform/how-to/add-deploy-do-button/

**Comment by kristoferlund** [comment]
This would require us to first package Praise into one Docker container. Which is totally doable. 

https://docs.digitalocean.com/products/app-platform/reference/app-spec/

**Comment by kristoferlund** [comment]
This would allow simplified deployment, for instance the "Deploy to DO" button - one click Praise installs.

**Comment by kkatusic** [comment]
Does this only work for the Digital Ocean?

**Comment by kristoferlund** [comment]
No, it would simplify deployment on other hosting providers as well. Have a look at the deployment page of this system – ChatWoot. 

https://www.chatwoot.com/deploy

Longterm goal would be to support simple deployment on a number of hosting providers, similar to that.
