### ISSUE TITLE
Allow access to the API using an API key

### ISSUE THREAD

**Issue by kristoferlund** [givepraise/praise#572]
Currently, to access the Praise API you need to authenticate by signing a message using Metamask or other ETH wallet. This is all well and good for individual users. But, we would like to open up API access to external systems as well. In this case Metamask authentication is not ideal.

We would like to add API key as an authentication method to allow external systems _read only_ (to begin with) access to the API.

## Settings 
- Generate and delete API key
- An API key can be given `full` or `limited` access.
  - `full` - includes everything, similar to what an ADMIN gets
  - `limited` - similar to what a USER gets 

## API access 
- API key is sent as a request header
- API key gives read only access to all applicable endpoints

**Comment by kristoferlund** [comment]
Adding a wireframe to detail how the key is generated.

<img width="637" alt="image" src="https://user-images.githubusercontent.com/9698363/189906442-b5345836-61b4-4ede-a972-f924460f5fb7.png">

**Comment by kristoferlund** [comment]
<img width="946" alt="image" src="https://user-images.githubusercontent.com/9698363/190978789-e058ccaa-911e-4f4c-bd09-da582736d51d.png">

**Comment by kristoferlund** [comment]
Added some details to the wireframes. API keys gets its own box under "Application settings".

https://miro.com/app/board/o9J_lyTkWjY=/

<img width="1558" alt="image" src="https://user-images.githubusercontent.com/9698363/191190513-62115cc8-c142-41f2-addd-cfa4352ec0cc.png">

**Comment by kkatusic** [comment]
Is there any example how this API keys will be sent throw headers in request? thx

**Comment by kristoferlund** [comment]
> Is there any example how this API keys will be sent throw headers in request? thx

I've discussed with @saucecodee which headers to use etc. @saucecodee perhaps you can push to a feature branch and create a "WIP" PR so we can follow the work?

**Comment by kristoferlund** [comment]
- Just realized that `res.locals.authRole` is not used for user authentication role but for the role requirement of the route in question. And it is not being used at all currently. Please remove it from the code, it is just confusing.
- Let's stick to `full`and `limited` for the API key access. I think it is more clear than `admin` and `user`, risking confusion with the user roles.
- Let's do like you proposed and add `res.locals.apiKey`. Then you can create utility functions to check permissions where needed. 
- Endpoint details:
  - /eventlogs/all
    - Hide eventLog contents if related to a period and period has status QUANTIFY and user is not (ADMIN or **APIKEY with full access**)
  - /eventlogs/types
  - /periods/all
  - /periods/single
  - /periods/:periodId/praise
  - /periods/:periodId/receiverPraise
  - /periods/:periodId/giverPraise
  - /periods/:periodId/quantifierPraise
  - /periods/:periodId/exportFull
    - Minimum auth: UserRole `USER` or APIKEY `limited`
    - If not UserRole `ADMIN` or APIKEY `full`, empty the following export fields:
      - TO ETH ADDRESS
      - FROM ETH ADDRESS
      - QUANTIFIER {X} ETH ADDRESS
  - /periods/:periodId/exportSummary    
    - Minimum auth: UserRole `USER` or APIKEY `limited`
  - /periods/:periodId/exportCustom
    - Minimum auth: UserRole `ADMIN` or APIKEY `full`
  - /periods/:periodId/verifyQuantifierPoolSize
    - Minimum auth: UserRole `USER` or APIKEY `limited`
  - /periodsettings/:periodId/settings/all
  - /periodsettings/:periodId/settings/:settingId
  - /praises/all
  - /praises/:id
  - /settings/all
  - /settings/:id
  - /settings/customExportTransformer
    - Minimum auth: UserRole `USER` or APIKEY `limited`
  - /users/all
    - If not UserRole `ADMIN` or APIKEY `full`, `ethereumAddress` is empty
  - /users/:id
    - If not UserRole `ADMIN` or APIKEY `full`, `ethereumAddress` is empty
