### ISSUE TITLE
Switching quantifier on Period doesn't update that state

### ISSUE THREAD

**Issue by kkatusic** [givepraise/praise#679]
https://user-images.githubusercontent.com/1242145/202688695-e165431c-8ab9-4f72-be9b-a2b38c54ce6e.mp4

1. Change/Switch quantifier on Period
2. Change current tab
3. Back to "Quantifier" tab

it doesn't update state on frontend

**Comment by kristoferlund** [comment]
Solved. UI now does a reload on quantifier switch.
