### ISSUE TITLE
Remove refreshToken and accessToken from database

### ISSUE THREAD

**Issue by kristoferlund** [givepraise/praise#772]
No longer needed. `accessToken` should never have been stored as it poses a huge security risk.

**Comment by CarlosQ96** [comment]
On top of this I found activeToken in the userAccount schema. I think it should be removed too.

**Comment by kristoferlund** [comment]
The activateToken is in use when users activate - connect their Discord to Praise and their eth address.

https://github.com/givepraise/praise/blob/726a2d4c84c75b6a17ea495854ad3cdabd838c36/packages/api2/src/activate/activate.service.ts#L56
