### ISSUE TITLE
Paginate `/periods/:id/praise` endpoint

### ISSUE THREAD

**Issue by kristoferlund** [givepraise/praise#773]
We should remove the endpoint completely and instead add a period query filter option to `/praise`. Or, we keep it but make the response paginated.

**Comment by kkatusic** [comment]
@kristoferlund, @nebs-dev help me and we fixed query problem, now I have another problem, I can find where is this list of praises is on the Frontend, if I try direct link:

http://localhost:3000/periods/634fa613d89a24acb3005ec3/praise

it takes me, better to said redirect mi to receivers page:

http://localhost:3000/periods/634fa613d89a24acb3005ec3/receivers

can you advice me how to get to that link/page?

thx
