### ISSUE TITLE
Loading period quantifier is really slow

### ISSUE THREAD

**Issue by kristoferlund** [givepraise/praise#812]
Example:
`/api/periods/626150bfc4014a719d287236/praise/quantifier/61ef29cf102583655ce10ab5`

**Comment by kkatusic** [comment]
@kristoferlund this would be paginated in future release, leave this comment only for notice
![local_298C48A1](https://user-images.githubusercontent.com/1242145/216432671-bdaca4d9-6770-4689-ad91-4ec956f34fec.png)
