### ISSUE TITLE
Typo in period defaults setting

### ISSUE THREAD

**Issue by kristoferlund** [givepraise/praise#820]
Change: "How many redundant quantifications are assigned to each praise?"
To: "How many quantifiers are assigned to each praise?"

<img width="730" alt="image" src="https://user-images.githubusercontent.com/9698363/217266439-34830841-0b10-4a18-806f-2d41f88e3ab0.png">

**Comment by Maniyuvan** [comment]
Hi, I can work on updating this.

**Comment by Maniyuvan** [comment]
Okay, will do that
