### ISSUE TITLE
Fix api2 linting errors

### ISSUE THREAD

**Issue by kristoferlund** [givepraise/praise#846]

**Comment by mohammadranjbarz** [comment]
https://github.com/givepraise/praise/pull/843#issuecomment-1431203091

<img width="1440" alt="Screen Shot 1401-11-27 at 00 03 30" src="https://user-images.githubusercontent.com/9850545/219148048-15464f2d-6424-4f0b-a2ed-1192c680941d.png">

**Comment by mohammadranjbarz** [comment]
We have some problems in running tests as well

<img width="1431" alt="Screen Shot 1401-11-30 at 10 03 01" src="https://user-images.githubusercontent.com/9850545/219932905-3598aace-6157-4251-a315-fdc399b77d65.png">

**Comment by kristoferlund** [comment]
Yes, the unit testing coverage is quite low and not at all up to date. The e2e testing coverage is better. Fixing unit tests is not a big priority at the moment.

`yarn workspace api2 test:e2e`

**Comment by mohammadranjbarz** [comment]
> Yes, the unit testing coverage is quite low and not at all up to date. The e2e testing coverage is better. Fixing unit tests is not a big priority at the moment.
> 
> `yarn workspace api2 test:e2e`
It has some failed test cases as well

<img width="1419" alt="Screen Shot 1401-12-01 at 09 20 57" src="https://user-images.githubusercontent.com/9850545/220020412-550b63ff-4c98-43f2-9652-7922659be836.png">
