### ISSUE TITLE
Create a types package for API input and response dtos

### ISSUE THREAD

**Issue by kristoferlund** [givepraise/praise#849]

**Comment by kristoferlund** [comment]
- Upgradee Node from v16.18.1 to current stable version v18.14.0
- `docker-compose-local.yml` now uses api2 instead of api
- package.json `api:start`now runs api2 instead of api
- Created a Dockerfile for api2
- New decorator `@EnforceAuthAndPermissions` joins the`BypassGuard`, `JwtGuard`, `ApiKeyGuard` and `PermissionsGuard` into a single decorator. User is authenticated if one of the authentication guards succeeds. Then the PermissionsGuard is used to check if the user has the required permissions.
- Created a Passport stategy; `BypassStrategy`. 
  - The strategy bypasses authentication for routes configured in the `BYPASS_ROUTE_AUTH` setting. 
  - If the strategy is activated a dummy user object with roles `["USER"]` is added to `req.user`.
  - To begin with the export endpoints bypasses authentication
- Migration to add `BYPASS_ROUTE_AUTH` to db

**Comment by kkatusic** [comment]
@kristoferlund is now `api2` branch stable version of it? no errors?

**Comment by kristoferlund** [comment]
Oh, put above comments on wrong issue. And to answer your question, no, not yet. But soon :) It has been soon for a number of weeks now.

**Comment by kristoferlund** [comment]
Duplicate to #873, closing.
