### ISSUE TITLE
Add `Communities` to database

### ISSUE THREAD

**Issue by kristoferlund** [givepraise/praise#851]
- Add a new collection – Communities.
- In this collection we store all details of the communities served by this Praise instance

```jsx
// DRAFT / IDEA

class Community {
  _id: Types.ObjectId;      // 0980987846534
  name: string;             // BanklessDAO
  hostname: string;         // banklessdao.givepraise.xyz
  owners: string[];         // [0x123, 0x345]
  discordGuildId: string;   // 0980987846534
  discordLinkNonce: string; // oiujoiuoo8u
  discordLinkState: string; // pending | active | (disabled?)
}
```

- Add field `Community` to all other collections to be able to distinguish data belonging to different communities

**Comment by mohammadranjbarz** [comment]
@kristoferlund 
I think these fields are needed as well:
* isPublic: boolean
* creator: string
