### ISSUE TITLE
Not able to give praise in Discord thread

### ISSUE THREAD

**Issue by kristoferlund** [givepraise/praise#876]
<img width="841" alt="image" src="https://user-images.githubusercontent.com/9698363/221176811-2033f959-0b91-42fe-81b0-1354653820ea.png">

**Comment by kristoferlund** [comment]
@Vyvy-vi I'm resurfacing this as praising in threads still don't work. Below is from the Praise Discord.

![Image](https://github.com/givepraise/praise/assets/9698363/92d965fd-39fc-4c88-9dc2-5542645e2bc3)

**Comment by kristoferlund** [comment]
@Vyvy-vi 

It works on my local test server. If this is a server config issue we need to detect that and inform somehow.

![Image](https://github.com/givepraise/praise/assets/9698363/35816398-b5d4-4dc1-8afb-2c78cd33f66f)

**Comment by kristoferlund** [comment]
@Vyvy-vi what did we conclude here?

1. The permissions string need to be changed for the bot invite, what should it say?
2. We need to update permissions on installed communities through Discord. What permission needs to be added?

But.. above does not fully solve issues right? As far as I remember, above solves issue with thread praising in public channels but not in permissioned channels (that bot has access to).

**Comment by Vyvy-vi** [comment]
perms integer - 274878285888

this would only partially fix the issue
