### ISSUE TITLE
Make sure all Github Actions run 

### ISSUE THREAD

**Issue by kristoferlund** [givepraise/praise#892]

**Comment by kristoferlund** [comment]
@mohammadranjbarz, one thing needed is to clean up the handling of secrets. See here:

```
      - run: echo "${{secrets.ROOT_ENV_TESTING }}" > .env
      - run: echo "${{secrets.API_ENV_TESTING }}" > packages/api2/.env
      - run: echo "${{secrets.DISCORDBOT_ENV_TESTING }}" > packages/discord-bot/.env
      - run: echo "${{secrets.FRONTEND_ENV_TESTING }}" > packages/frontend/.env
```

Long time ago we used separate env files for the different services. Not any longer. So, this part can be cleaned up. Let me know if you need additional permissions to access secrets.

**Comment by kristoferlund** [comment]
Another issue, the frontend and discord bot builds need to have access to api-types package

**Comment by mohammadranjbarz** [comment]
@kristoferlund  said

* On creation of PR / new commit to feature branch
   * Run CI/CD to verify build / lint

* On PR merge / commit to main branch. 
   * Build new development images
   * Image name: praise-dev/api
   * (same for frontend etc)

* When creating a new release:
   * Build new production images
   * Image name: praise/api
   * (same for frontend etc)
