### ISSUE TITLE
We need a way to create new communities - A script?

### ISSUE THREAD

**Issue by kristoferlund** [givepraise/praise#909]
Until we have the SetupWeb available we need a way to create new communities.

**Comment by mohammadranjbarz** [comment]
@kristoferlund 
I was thinking about it, either we should write an script that execute query on db and directly create community that it would need to write lots of repetitive codes or we can implement new endpoint for this purpose that uses current communityServiceFunctions and just write a mini script that can call that endpoint with an api-key
WDYT?

**Comment by kristoferlund** [comment]
@mohammadranjbarz then you can use API key defined in .env, not in database since those are community specific
