### ISSUE TITLE
Configure staging server to run multiple communities with the new setup.

### ISSUE THREAD

**Issue by kristoferlund** [givepraise/praise#910]
- praise1.givepraise.xyz
- praise2.givepraise.xyz
- praise3.givepraise.xyz

**Comment by mhmdksh** [comment]
@kristoferlund What is the new setup??? How is it different than what is currently running?? Do you mean the multi-setup??

**Comment by kristoferlund** [comment]
@mhmdksh 

Exactly. We want to setup staging like this:
- 1 frontend
- 1 bot
- 1 api
- 3 databases

This setup should support 3 test communities. Which means we also need 3 test discord guilds.

**Comment by kristoferlund** [comment]
Which also means we need a way to create new communities. Creating a new community when server is already setup should require only two steps:
- Create community record and database
- Config DNS 

Perhaps we can run the setupweb to create community record and database? Without fancy design. @nebs-dev ?

**Comment by mhmdksh** [comment]
> Which also means we need a way to create new communities. Creating a new community when server is already setup should require only two steps:
> 
> * Create community record and database
> * Config DNS
> 
> Perhaps we can run the setupweb to create community record and database? Without fancy design. @nebs-dev ?

For configuring DNS we can use cloudflare APIs, check these links:

https://www.npmjs.com/package/cloudflare
https://developers.cloudflare.com/pages/platform/functions/typescript/

**Comment by kristoferlund** [comment]
@mhmdksh great! But perhaps even easier would be to use a wildcard record and route all traffic to `*.givepraise.xyz` to our server?

**Comment by mhmdksh** [comment]
> @mhmdksh great! But perhaps even easier would be to use a wildcard record and route all traffic to `*.givepraise.xyz` to our server?

I think it's a good idea to find easier ways. If it works and can be handled from caddy and from within the app, then yeah why not. 
But ***.givepraise.xyz** would not be efficient. Basically this will block us from using any other subdomain in the future. Maybe ***.cloud.givepraise.xyz** would make more sense...

**Comment by kristoferlund** [comment]
There is no issue with running wildcard domains together with statically defined.

We don't want to use the cloudflare api because that introduces an external dependency. We can not require those communities that want to self host to have their domains on Cloudflare, right?

It is important that the domain name a community gets is a "good" domain name. This name will be shared within the community and externally, for example:

`You can find my contributor profile and bio at http://refidao.givepraise.xyz/kristofer`

So, let's try to work with wildcard domains. @mohammadranjbarz will implement a "blocklist" in the api so that communities don't choose disallowed names such as "www" or "mail". See #924

**Comment by kristoferlund** [comment]
@mhmdksh There are some small things to finish up before fully closing this:

- Add short text to README and About section on GitHub
- Make sure repo is in sync with what we are actually using on the server
  - Only one docker-compose file is on the server, in repo there are two
  - Remove all `.dev.sh` scripts and make sure the remaining scripts work

**Comment by kristoferlund** [comment]
@mhmdksh There is some issue with how the frontend is setup. I need to be able to run the `upgrade.sh` script after pushing a new version to github. This now gives me error:

<img width="932" alt="image" src="https://user-images.githubusercontent.com/9698363/233331710-4ab68660-0150-485e-b3cb-e23b081f5f5b.png">

**Comment by mhmdksh** [comment]
@kristoferlund  this has been fixed in the latest commits, please check: https://github.com/givepraise/praise-staging/commit/e7e95c313c54e9ec62d96acec944767fb9e5849c

> @mhmdksh There are some small things to finish up before fully closing this:
> 
> * Add short text to README and About section on GitHub
> * Make sure repo is in sync with what we are actually using on the server
>   
>   * Only one docker-compose file is on the server, in repo there are two
>   * Remove all `.dev.sh` scripts and make sure the remaining scripts work

I still need to add some readme instructions
