### ISSUE TITLE
Complete staging setup, test end to end

### ISSUE THREAD

**Issue by kristoferlund** [givepraise/praise#959]
- [x] Staging backend running
- [x] Staging frontend running
- [x] Setup two test communities
- [ ] Create an automated deployment pipeline for the Praise-Web backend @mhmdksh
- [x] Create two discord test communities @kristoferlund 
- [x] Connect new discord bot to staging backend @Vyvy-vi @nebs-dev 
- [x] Create a third community using the setup web, full approval flow with discord bot @nebs-dev @Vyvy-vi 
- [x] Give praise in newly setup community, check all looks good

**Comment by mhmdksh** [comment]
@kristoferlund I've added 1 more step to keep the Praise-Web repo updated with the latest images, I've opened that as a separate issue here: https://github.com/givepraise/praise/issues/963
