### ISSUE TITLE
Cleanup domain names and terminology

### ISSUE THREAD

**Issue by kristoferlund** [givepraise/praise#965]
There are a lot of domain names and similar sounding terms flying around these days. Let's clean up before we have the production setup done.

Below are some initial ideas, eager to hear you feedback @mhmdksh @mohammadranjbarz @nebs-dev @kkatusic @Vyvy-vi 

## api
- Production: `saas.givepraise.xyz`
- Staging: `saas.dev.givepraise.xyz`

## dashboard
Base domain is same as for api:
- Production: `saas.givepraise.xyz`
- Staging: `saas.dev.givepraise.xyz`

Default community domains use a wildcard DNS record and point toward base domain:
- Production: `[communityname].givepraise.xyz`
- Staging: `[communityname].dev.givepraise.xyz`

Community domains point a CNAME record to base domain:
- Production: `anydomain.com` points to `saas.givepraise.xyz`
- Staging: `anydomain.com` points to `saas.dev.givepraise.xyz`

## web
- Production: `givepraise.xyz`
- Staging: `dev.givepraise.xyz`

**Comment by mhmdksh** [comment]
> There are a lot of domain names and similar sounding terms flying around these days. Let's clean up before we have the production setup done.
> 
> Below are some initial ideas, eager to hear you feedback @mhmdksh @mohammadranjbarz @nebs-dev @kkatusic @Vyvy-vi
> 
> ## api
> * Production: `saas.givepraise.xyz`
> * Staging: `saas.dev.givepraise.xyz`
> 
> ## dashboard
> Base domain is same as for api:
> 
> * Production: `saas.givepraise.xyz`
> * Staging: `saas.dev.givepraise.xyz`
> 
> Default community domains use a wildcard DNS record and point toward base domain:
> 
> * Production: `[communityname].givepraise.xyz`
> * Staging: `[communityname].dev.givepraise.xyz`
> 
> Community domains point a CNAME record to base domain:
> 
> * Production: `anydomain.com`
> * Staging: `anydomain.com`
> 
> ## web
> * Production: `givepraise.xyz`
> * Staging: `dev.givepraise.xyz`

Hey @kristoferlund These names sound good. This won't affect anything current implementation I guess. All good from my end.

**Comment by kkatusic** [comment]
What will be user domain final API URL? for example I have _mydomainpraise.com_ what will be my API URL?

**Comment by kristoferlund** [comment]
> Hey @kristoferlund These names sound good. This won't affect anything current implementation I guess. All good from my end.

Good. But yes, the names will effect all we have deployed so far  :) Or do you mean something else? All current domains etc need to be changed to match this structure.

**Comment by kristoferlund** [comment]
> @kkatusic What will be user domain final API URL? for example I have mydomainpraise.com what will be my API URL?

It will be `mydomainpraise.com/api`.

And `mydomainpraise.com` will be configured with a CNAME DNS record pointing to `saas.givepraise.xyz`.

**Comment by kristoferlund** [comment]
@nebs-dev @mhmdksh So, for the deployment of the web repository the setup would be like this:

![Image](https://user-images.githubusercontent.com/9698363/235665504-8507ee73-d0bd-407c-a118-81eb64624083.png)
