### ISSUE TITLE
Blank page after clicking on username

### ISSUE THREAD

**Issue by kkatusic** [givepraise/praise#979]
When you go to _Period_ page, than choose either _GIvers_ or _Quantifiers_ and than choose some person you got list of praises. But when you try click on some user name on list, either giver or receiver you are getting blank page.

Ecample URL: https://one.dev.givepraise.xyz/periods/6298c77e03286dcbe3bc1336/quantifier/61f0839d102583655ce15a56

**Comment by kristoferlund** [comment]
This one is fixed I believe
