### ISSUE TITLE
Set correct permissions for Praise apps on Discord

### ISSUE THREAD

**Issue by kristoferlund** [givepraise/praise#997]
This goes for both the staging app and the production app.

We should set only the minimal permissions needed for the app to be able to fetch available guilds. @Vyvy-vi perhaps have some insight into which permissions are needed?

# Current permissions

![Image](https://user-images.githubusercontent.com/9698363/236406305-06a7b72c-bffd-42f9-95fc-2665d807baa2.png)

**Comment by Vyvy-vi** [comment]
We _need_ the following permissions - 
- Send Messages
- Send Messages in threads
- Embed Links
- Attach Files
- Read Messages / View Channels

We may potentially need these in future -
- Read Message History 
- Use External Emojis (if we update the bot to use custom praise-themed emojis, it would need this perm)
- Manage Webhooks (this can potentially be used to set up a webhook in a discord server, which can be used to create a notification feed for the bot)

**Comment by kristoferlund** [comment]
@Vyvy-vi the permissions you list are for the bot to work, right? The question was regarding the permissions needed for our Discord app to be able to fetch guilds when integrated with the setup web.

**Comment by Vyvy-vi** [comment]
Oh, I misunderstood.
If this is using the Oauth2 API, we need the _scopes_ `identify` and `guilds`

**Comment by nebs-dev** [comment]
@Vyvy-vi I don't see those permissions that you mentioned in the app OAuth2 options ( check Kristofer's screenshot )

**Comment by Vyvy-vi** [comment]
the default In-App Authorization has those scopes by default

**Comment by kristoferlund** [comment]
Closing this as resolved.
